name: captcha_private_update_trigger

on:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger workflow in another repository
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PROSOPONATOR_PAT }}
          script: |
            const response = await github.repos.createDispatchEvent({
              owner: 'goastler',
              repo: 'gha-b',
              event_type: 'captcha_updated'
            });
            console.log(response);
